import type { Metadata } from "next";
// import { Inter, IBM_Plex_Mono } from "next/font/google";
import { inter } from "@/utils/fonts";
import "./globals.css";
import MainNavbar from "@/components/navbar/main-navbar";

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
// });
// const ibmPlexMono = IBM_Plex_Mono({
//   subsets: ["latin"],
//   weight: ["300", "400", "500"],
//   variable: "--font-ibm-plex-mono",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainNavbar />
        {children}
      </body>
    </html>
  );
}
